import { Product } from "@/types/product";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    price: 79900,
    description: "High-quality wireless headphones with active noise cancellation and exceptional sound quality.",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=800&fit=crop",
    category: "Electronics",
    inStock: true,
  },
  {
    id: "2",
    name: "Luxury Watch Collection",
    price: 299900,
    description: "Elegant timepiece with Swiss movement and sapphire crystal glass.",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=800&fit=crop",
    category: "Accessories",
    inStock: true,
  },
  {
    id: "3",
    name: "Designer Handbag",
    price: 189900,
    description: "Premium leather handbag with classic design and modern functionality.",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&h=800&fit=crop",
    category: "Fashion",
    inStock: true,
  },
  {
    id: "4",
    name: "Smart Fitness Tracker",
    price: 14900,
    description: "Track your health and fitness goals with advanced sensors and long battery life.",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&h=800&fit=crop",
    category: "Electronics",
    inStock: true,
  },
  {
    id: "5",
    name: "Professional Camera",
    price: 129900,
    description: "Mirrorless camera with 4K video and advanced autofocus system.",
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&h=800&fit=crop",
    category: "Electronics",
    inStock: true,
  },
  {
    id: "6",
    name: "Minimalist Backpack",
    price: 1000,
    description: "Stylish and practical backpack perfect for daily commute and travel.",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop",
    category: "Accessories",
    inStock: true,
  },
  {
    id: "7",
    name: "Wireless Mechanical Keyboard",
    price: 12900,
    description: "Mechanical keyboard with premium switches and customizable RGB lighting.",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&h=800&fit=crop",
    category: "Electronics",
    inStock: true,
  },
  {
    id: "8",
    name: "Designer Sunglasses",
    price: 24900,
    description: "UV protection sunglasses with polarized lenses and premium frame.",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&h=800&fit=crop",
    category: "Accessories",
    inStock: true,
  },
];
